spring.application.name=backend
#server.port=8081
spring.mongodb.uri=mongodb+srv://admin:Mustafa%40123@mustafa01.crrhmo6.mongodb.net/backend?retryWrites=true&w=majority
#spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}